### ISSUE TITLE
Logging, error handling, and local folder in data.py

### ISSUE THREAD

**Issue by cassianobecker** [cassianobecker/tgcn2#10]
1. check for credentials and issue logger.error() if empty
2. pass only relative path to downloader.load() (local path should be appended inside load(), from local_directory property read from hcp_database.ini file at constructor);
3. include error/info/debug messages in data and downloader (with different logger objects and different logger levels set and read from hcp_database.ini files) - displayed messages should include content from variables involved (url's, number of subjects, error codes, etc);
4. treat return messages other than 200 in downloader and issue logger.error() if it is the case; invert the if/else flow for positive debug message when file is found locally

**Comment by semihcanturk** [comment]
INFO for list of subjects, and for each subject in data.py, and for the request in downloader
DEBUG for each type of file processing in data.py, and for file saving in downloader.py
ERROR for file not found in data.py, and for code other that 200 in downloader
DEBUG for code 200 in downloader.py

**Comment by cassianobecker** [comment]
the ini files should be located in specific folder hcp/dataset/conf

**Comment by cassianobecker** [comment]
the logger construction/configuration in the classes HcpDownloader, DtiDownloader, HcpDataset seems involved and results in duplicated code in these classes. Could you define convenience methods in a common module 'logging.py' inside package 'util'?
