### ISSUE TITLE
Improve behavior of downloader wrt missing files

### ISSUE THREAD

**Issue by semihcanturk** [cassianobecker/tgcn2#2]
e.g. missing physio_log

**Comment by semihcanturk** [comment]
Current solution proposal :
1) We delete the whole folder content of that subject
2) we create an 'exception list' of incomplete_subjects.txt
3) each time the dataloader processes the list of subjects, it looks in the above file to check if the subject is in that list, then issues a WARNING and skips to the next subject

**Comment by cassianobecker** [comment]
Include an option on [FMRI] regress_physio = False (or True), and skip  the call to get_vitals () if False.

If True, and physio files are not there for a given patient, we log.WARNING 'patient XX doesn't have physio information, skipping'  and the user can then remove that specific subject from the list of subjects in the future.

**Comment by cassianobecker** [comment]
Moreover, should add a 'configurable' number of retries in the downloader ini (like 3) and retry after a delay of (say 5s, another parameter) each time
