### ISSUE TITLE
Cleaning data loader

### ISSUE THREAD

**Issue by semihcanturk** [cassianobecker/tgcn2#7]
getting rid of old classes & aux functions in a single commit,
integrate encode_x and encode_y as member functions of the SlidingWindow class

**Comment by cassianobecker** [comment]
rename HCPDowloader to HcpDowloader; GitDownloader to DtiDownloader

**Comment by cassianobecker** [comment]
remove imports used by MatlabDataset and StreamMatlabDataset

**Comment by cassianobecker** [comment]
encode_y has a complicated method signature
change to yoh = encode_y(C, shape_X)
and get the numbers you need inside encode_y and/or from self (for Gp, Gn, H)

**Comment by cassianobecker** [comment]
there are unused imports left in torch_data.py
